### ISSUE TITLE
Adding a method to ChaiProvider seems to break UserPasswordPolicyReader (when exposing ldap rename)

### ISSUE THREAD

**Issue by watery** [ldapchai/ldapchai#16]
Hello,
I'm writing a web service supporting [pwm](https://github.com/pwm-project/pwm) user registration.

I'm trying to expose the [LDAPConnection.rename()](https://www.novell.com/documentation/developer/jldap/jldapenu/api/com/novell/ldap/LDAPConnection.html#rename(java.lang.String,%20java.lang.String,%20java.lang.String,%20boolean)) method, but after my changes user login within pwm no longer works &mdash; pwm is configured against an eDirectory LDAP, therefore I've changed `JLDAPProviderImpl`.

The error is this:

```
2018-03-21T11:17:52Z, ERROR, servlet.AbstractPwmServlet, {1286,admin} unexpected error during action handler for 'password.pwm.http.servlet.LoginServlet:restLogin', error: null [127.0.0.1] (stacktrace follows)
java.lang.NullPointerException
	at com.sun.jndi.ldap.LdapCtx.extendedOperation(LdapCtx.java:3268)
	at com.novell.ldapchai.provider.JNDIProviderImpl.extendedOperation(JNDIProviderImpl.java:405)
	at com.novell.ldapchai.provider.WatchdogWrapper.extendedOperation(WatchdogWrapper.java:190)
	at com.novell.ldapchai.impl.edir.entry.EdirEntries$UserPasswordPolicyReader.findNspmPolicyForUser(EdirEntries.java:374)
	at com.novell.ldapchai.impl.edir.entry.EdirEntries$UserPasswordPolicyReader.readPasswordPolicy(EdirEntries.java:323)
	...
```

I can't get why my change breaks user login: should I edit other parts of the library?

This is the code I'm working on:

```
diff --git a/pom.xml b/pom.xml
index 60dfb63..e11ea2e 100644
--- a/pom.xml
+++ b/pom.xml
@@ -9,7 +9,7 @@
     </parent>
 
     <groupId>com.github.ldapchai</groupId>
-    <version>0.7.0</version>
+    <version>0.7.1</version>
     <artifactId>ldapchai</artifactId>
     <packaging>jar</packaging>
 
diff --git a/src/main/java/com/novell/ldapchai/provider/AbstractProvider.java b/src/main/java/com/novell/ldapchai/provider/AbstractProvider.java
index 599f7b1..f6b14a0 100644
--- a/src/main/java/com/novell/ldapchai/provider/AbstractProvider.java
+++ b/src/main/java/com/novell/ldapchai/provider/AbstractProvider.java
@@ -296,6 +296,24 @@ abstract class AbstractProvider implements ChaiProvider, ChaiProviderImplementor
                 throw new NullPointerException( "entryDN must not be null" );
             }
         }
+        
+        @Override
+        public final void modifyEntryRdn(final String entryDN, final String newRDN, final String newParentDN, final boolean deleteOldRDN) {
+        	if ( newParentDN == null )
+            {
+                throw new NullPointerException( "newParentDN must not be null" );
+            }
+
+            if ( newRDN == null )
+            {
+                throw new NullPointerException( "newRDN must not be null" );
+            }
+
+            if ( entryDN == null )
+            {
+                throw new NullPointerException( "entryDN must not be null" );
+            }
+        }
 
         public final void deleteEntry( final String entryDN )
         {
diff --git a/src/main/java/com/novell/ldapchai/provider/ApacheLdapProviderImpl.java b/src/main/java/com/novell/ldapchai/provider/ApacheLdapProviderImpl.java
index daedcbc..b290a07 100644
--- a/src/main/java/com/novell/ldapchai/provider/ApacheLdapProviderImpl.java
+++ b/src/main/java/com/novell/ldapchai/provider/ApacheLdapProviderImpl.java
@@ -19,6 +19,7 @@
 
 package com.novell.ldapchai.provider;
 
+import com.novell.ldap.LDAPException;
 import com.novell.ldapchai.ChaiConstant;
 import com.novell.ldapchai.ChaiRequestControl;
 import com.novell.ldapchai.exception.ChaiError;
@@ -308,6 +309,13 @@ public class ApacheLdapProviderImpl extends AbstractProvider implements ChaiProv
         }
     }
 
+    @ChaiProvider.LdapOperation
+    @ChaiProvider.ModifyOperation
+    public void modifyEntryRdn(String entryDN, String newRDN, String newParentDN, boolean deleteOldRDN)
+    		throws ChaiOperationException, ChaiUnavailableException, IllegalStateException {
+    	throw ChaiOperationException.forErrorMessage( "Not implemented" );
+    }
+
     public void deleteEntry( final String entryDN )
             throws ChaiOperationException, ChaiUnavailableException, IllegalStateException
     {
diff --git a/src/main/java/com/novell/ldapchai/provider/ChaiProvider.java b/src/main/java/com/novell/ldapchai/provider/ChaiProvider.java
index fd88fee..5786104 100644
--- a/src/main/java/com/novell/ldapchai/provider/ChaiProvider.java
+++ b/src/main/java/com/novell/ldapchai/provider/ChaiProvider.java
@@ -124,6 +124,19 @@ public interface ChaiProvider
     void createEntry( String entryDN, Set<String> baseObjectClasses, Map<String, String> stringAttributes )
             throws ChaiOperationException, ChaiUnavailableException, IllegalStateException;
 
+    /**
+     * Delete the specified entry.
+     *
+     * @param entryDN A valid entryDN
+     * @throws ChaiOperationException   If an error is encountered during the operation
+     * @throws ChaiUnavailableException If no directory servers are reachable
+     * @throws IllegalStateException    If the underlying connection is not in an available state
+     */
+    @ChaiProvider.LdapOperation
+    @ChaiProvider.ModifyOperation
+    void modifyEntryRdn(String entryDN, String newRDN, String newParentDN, boolean deleteOldRDN)
+            throws ChaiOperationException, ChaiUnavailableException, IllegalStateException;
+
     /**
      * Delete the specified entry.
      *
diff --git a/src/main/java/com/novell/ldapchai/provider/JLDAPProviderImpl.java b/src/main/java/com/novell/ldapchai/provider/JLDAPProviderImpl.java
index 0094888..b96bb9d 100644
--- a/src/main/java/com/novell/ldapchai/provider/JLDAPProviderImpl.java
+++ b/src/main/java/com/novell/ldapchai/provider/JLDAPProviderImpl.java
@@ -229,6 +229,20 @@ public class JLDAPProviderImpl extends AbstractProvider implements ChaiProviderI
         }
     }
 
+    @ChaiProvider.LdapOperation
+    @ChaiProvider.ModifyOperation
+    public void modifyEntryRdn(String entryDN, String newRDN, String newParentDN, boolean deleteOldRDN)
+    		throws ChaiOperationException, ChaiUnavailableException, IllegalStateException {
+    	try
+        {
+    		ldapConnection.rename(entryDN, newRDN, newParentDN, deleteOldRDN);
+        }
+        catch ( LDAPException e )
+        {
+            throw ChaiOperationException.forErrorMessage( e.getLDAPErrorMessage() );
+        }
+    }
+
     @ChaiProvider.LdapOperation
     @ChaiProvider.ModifyOperation
     public void deleteEntry( final String entryDN )
diff --git a/src/main/java/com/novell/ldapchai/provider/JNDIProviderImpl.java b/src/main/java/com/novell/ldapchai/provider/JNDIProviderImpl.java
index d82ad7a..67a0e28 100644
--- a/src/main/java/com/novell/ldapchai/provider/JNDIProviderImpl.java
+++ b/src/main/java/com/novell/ldapchai/provider/JNDIProviderImpl.java
@@ -332,6 +332,13 @@ public class JNDIProviderImpl extends AbstractProvider implements ChaiProviderIm
         }
     }
 
+    @ChaiProvider.LdapOperation
+    @ChaiProvider.ModifyOperation
+    public void modifyEntryRdn(String entryDN, String newRDN, String newParentDN, boolean deleteOldRDN)
+    		throws ChaiOperationException, ChaiUnavailableException, IllegalStateException {
+    	throw ChaiOperationException.forErrorMessage( "Not implemented" );
+    }
+
     @LdapOperation
     @ModifyOperation
     public final void deleteEntry( final String entryDN )
diff --git a/src/main/java/com/novell/ldapchai/provider/WatchdogWrapper.java b/src/main/java/com/novell/ldapchai/provider/WatchdogWrapper.java
index c37a467..8b12d46 100644
--- a/src/main/java/com/novell/ldapchai/provider/WatchdogWrapper.java
+++ b/src/main/java/com/novell/ldapchai/provider/WatchdogWrapper.java
@@ -19,27 +19,27 @@
 
 package com.novell.ldapchai.provider;
 
-import com.novell.ldapchai.ChaiEntryFactory;
-import com.novell.ldapchai.ChaiRequestControl;
-import com.novell.ldapchai.ChaiUser;
-import com.novell.ldapchai.exception.ChaiException;
-import com.novell.ldapchai.exception.ChaiOperationException;
-import com.novell.ldapchai.exception.ChaiUnavailableException;
-import com.novell.ldapchai.util.ChaiLogger;
-import com.novell.ldapchai.util.SearchHelper;
-
-import javax.naming.ldap.ExtendedRequest;
-import javax.naming.ldap.ExtendedResponse;
 import java.time.Duration;
 import java.time.Instant;
 import java.util.List;
 import java.util.Map;
 import java.util.Set;
 import java.util.concurrent.atomic.AtomicInteger;
-
 import java.util.concurrent.locks.ReadWriteLock;
 import java.util.concurrent.locks.ReentrantReadWriteLock;
 
+import javax.naming.ldap.ExtendedRequest;
+import javax.naming.ldap.ExtendedResponse;
+
+import com.novell.ldapchai.ChaiEntryFactory;
+import com.novell.ldapchai.ChaiRequestControl;
+import com.novell.ldapchai.ChaiUser;
+import com.novell.ldapchai.exception.ChaiException;
+import com.novell.ldapchai.exception.ChaiOperationException;
+import com.novell.ldapchai.exception.ChaiUnavailableException;
+import com.novell.ldapchai.util.ChaiLogger;
+import com.novell.ldapchai.util.SearchHelper;
+
 /**
  * A {@link ChaiProvider} implementation wrapper that handles automatic idle disconnects.
  *
@@ -170,6 +170,12 @@ class WatchdogWrapper implements ChaiProviderImplementor
         providerHolder.getProvider().deleteEntry( entryDN );
     }
 
+    @Override
+    public void modifyEntryRdn(String entryDN, String newRDN, String newParentDN, boolean deleteOldRDN)
+    		throws ChaiOperationException, ChaiUnavailableException, IllegalStateException {
+    	providerHolder.getProvider().modifyEntryRdn( entryDN, newRDN, newParentDN, deleteOldRDN );
+    }
+
     @Override
     public void deleteStringAttributeValue( final String entryDN, final String attributeName, final String value )
             throws ChaiOperationException, ChaiUnavailableException, IllegalStateException

```

Can you give me any hint?

**Comment by watery** [comment]
Nevermind, it looks like the problem is using `ldapchai` from an Eclipse workspace project as dependency.

I've manually run Maven to compile and install the library from the command line to the local repository and the login works again.
